version: '{branch}-{build}'

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
    - PYTHON: C:\Python35-x64
      PYTHON_VERSION: 3.5
    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7

matrix:
  fast_finish: true

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade -r requirements-dev.txt

build: off

test_script:
  - python setup.py test
